# Generated by Django 2.0.7 on 2018-08-25 09:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(help_text='学生番号を入力してください. (ex. s0000000)', max_length=7, unique=True)),
                ('name', models.CharField(help_text='名前を入力してください.', max_length=100)),
                ('grade', models.CharField(help_text='学年を選択してください.', max_length=2)),
                ('phone_number', models.CharField(blank=True, help_text='電話番号を入力してください.', max_length=13)),
                ('is_staff', models.BooleanField(default=False, help_text='ユーザが管理サイトにアクセスできるかを指定する.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='有効なユーザとして扱うかを指定する.', verbose_name='active')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(help_text='所属している局・部門を選択してください.', to='account.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
