# Generated by Django 2.0.7 on 2018-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(help_text='学生番号を入力してください. (ex. s16312786)', max_length=9, unique=True),
        ),
    ]
