# Generated by Django 2.0.7 on 2018-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180826_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
