# Generated by Django 2.0.7 on 2018-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=10)),
                ('weather', models.CharField(max_length=10)),
                ('_0600', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0630', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0700', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0730', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0800', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0830', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0900', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_0930', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1000', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1030', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1100', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1130', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1200', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1230', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1300', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1330', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1400', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1430', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1500', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1530', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1600', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1630', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1700', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1730', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1800', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1830', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1900', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_1930', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2000', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2030', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2100', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2130', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2200', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2230', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2300', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('_2330', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shifts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('user', 'day', 'weather')},
        ),
    ]
