# Generated by Django 2.0.7 on 2018-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_shift_shift_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='department',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
