# Generated by Django 2.1 on 2018-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='sheet_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
